# netlify.toml
# Configuration for Netlify Hosting

[build]
  publish = "www.spx6900.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
